# Use root/example as user/password credentials
version: '3.1'

services:

  mongo_db:
    container_name: mongoDB
    image: mongo
    ports:
    - 2017:2017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword
      ME_CONFIG_MONGODB_SERVER: mongo_db
      ME_CONFIG_MONGODB_URL: mongodb://root:rootpassword@mongo_db:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - "mongo_db"
